name: Go Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Upload - Profile.sxcu'
      - '.gitignore'
      - '.github/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5.1.0
      with:
        go-version: 1.23.0
        check-latest: true
